language: node_js
node_js:
- '0.10'
after_script:
  - cat lcov.info | codeclimate
notifications:
  slack: everestps:KMgLvTP2eVQhyK6KCfaAjO5M
deploy:
  provider: heroku
  api_key:
    secure: UVnL4+v1kExxAuhNR+sHu0e33zBSv0hzXKtupWYV+8btxLY2eTOgQSMNAx3avAZKyVWKCF1r07XhZiYy2RbUcBCrhQ0bwRy6S5VjYf29bIDLXxE+Z0FxU22zVCq3rlRHBg6dGc8l7nGNe2SkBoZB2DNktk+xGc+QOShsH30Dzfk=
  app: borderly
  on:
    repo: borderly/borders
services:
  - mongodb
addons:
  code_climate:
    repo_token: "X+CwnMOzlDcusyyyk75KbWKCCAkGY/WyxDTDB1kEYGt73t+rLiEErwQes9L5D9lynp1MZ4gJyu37V2pcR5kuqeG2qzM2yLaW8GiAJxY4ZU+p40O2eUVn8N1DrwQ1MVxFdADXUNaA5kVHLK7xT3O97UqIbK48AV4W3IIrhr0DEWw="
