language: node_js
node_js:
- '0.10'
notifications:
  slack: everestps:KMgLvTP2eVQhyK6KCfaAjO5M
deploy:
  provider: heroku
  api_key:
    secure: UVnL4+v1kExxAuhNR+sHu0e33zBSv0hzXKtupWYV+8btxLY2eTOgQSMNAx3avAZKyVWKCF1r07XhZiYy2RbUcBCrhQ0bwRy6S5VjYf29bIDLXxE+Z0FxU22zVCq3rlRHBg6dGc8l7nGNe2SkBoZB2DNktk+xGc+QOShsH30Dzfk=
  app: borderly
  on:
    repo: borderly/borders
